In [1]:
import numpy as np
import sklearn.datasets as load_diabetes
import sklearn.datasets as load_diabetes

In [2]:
# X, y = load_diabetes(return_X_y=True)
X, y = load_diabetes.load_diabetes(return_X_y=True)

In [3]:
print(X.shape, y.shape)

(442, 10) (442,)


In [4]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [5]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [7]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(353, 10) (89, 10) (353,) (89,)


In [8]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [9]:
reg.fit(X_train, y_train)

LinearRegression()

In [10]:
y_pred = reg.predict(X_test)

In [11]:
from sklearn.metrics import r2_score

In [12]:
r2_score(y_test, y_pred)

0.4399338661568968

In [13]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [14]:
reg.intercept_

151.88331005254167

# Multile Linea Regression

In [15]:
%pip install plotly

import numpy as np
import pandas as pd
from sklearn.datasets import make_regression

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

Note: you may need to restart the kernel to use updated packages.


In [16]:
from sklearn.datasets import make_regression

In [17]:
X, y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [18]:
df = pd.DataFrame({'feature1': X[:, 0], 'feature2': X[:, 1], 'target': y})

In [19]:
print(df.shape)

(100, 3)


In [20]:
df.head()

,feature1,feature2,target
0,0.247631,-1.033790,-64.292882
1,-0.652603,0.488743,44.672359
2,-0.480546,-1.300289,-104.703417
3,0.002252,0.871864,76.332455
4,-1.051931,-0.359540,16.774106


In [21]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target', title='3D Scatter Plot of Features and Target')
fig.show()

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
lr = LinearRegression()


In [25]:
lr.fit(X_train, y_train)

LinearRegression()

In [26]:
y_pred = lr.predict(X_test)

In [27]:
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R^2 Score:", r2_score(y_test, y_pred))
print("Adjusted R^2 Score:", 1 - (((1 - r2_score(y_test, y_pred)) * (len(y_test) - 1)) / (len(y_test) - X_test.shape[1] - 1)))

Mean Absolute Error: 44.408521864100315
Mean Squared Error: 2983.1116491344947
Root Mean Squared Error: 54.61786932071311
R^2 Score: 0.4074233033185636
Adjusted R^2 Score: 0.33770839782662987


In [ ]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
XGrid, yGrid = np.meshgrid(x, y)

final  = np.vstack((XGrid.ravel().reshape(-1, 100), yGrid.ravel().reshape(-1, 100))).T
z_final = lr.predict(final).reshape(10, 10)
z = z_final

In [15]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target', title='3D Scatter Plot of Features and Target')
# fig.add_trace(go.Surface(x=x, y=y, z=z, colorscale='Viridis', opacity=0.5, name='Regression Plane'))
fig.add_trace(go.Surface(x=x, y=y, z=z))

fig.show()

In [16]:
lr.coef_
lr.intercept_

print("Coefficient:", lr.coef_)
print("Intercept:", lr.intercept_)

Coefficient: [20.35047308 71.35642593]
Intercept: 11.489704731326093
